"""Typed, declarative widget primitives.

Widgets form the intermediate representation (IR): a tree of Pydantic models the
reconciler diffs and the leaf renderers apply. Import them from this package
level rather than from submodules.
"""

from tempestroid.widgets.animated import (
    Animated,
    AnimatedList,
    Hero,
    Shimmer,
    Skeleton,
)
from tempestroid.widgets.base import (
    Component,
    DateChangeHandler,
    DismissHandler,
    EndReachedHandler,
    EventHandler,
    FileSelectHandler,
    LongPressHandler,
    MenuSelectHandler,
    RefreshHandler,
    RouteChangeHandler,
    ScrollHandler,
    SlideHandler,
    SwipeHandler,
    TapHandler,
    TextChangeHandler,
    ToggleHandler,
    Widget,
    handler_accepts_event,
)
from tempestroid.widgets.button import Button
from tempestroid.widgets.events import (
    DateChangeEvent,
    DismissEvent,
    EndReachedEvent,
    Event,
    EventValidationError,
    FileSelectEvent,
    LongPressEvent,
    MenuSelectEvent,
    RefreshEvent,
    RouteChangeEvent,
    ScrollEvent,
    SlideEvent,
    SwipeDirection,
    SwipeEvent,
    TapEvent,
    TextChangeEvent,
    ToggleEvent,
    parse_event,
)
from tempestroid.widgets.gestures import GestureDetector
from tempestroid.widgets.indicators import ProgressBar, Spinner
from tempestroid.widgets.inputs import (
    Checkbox,
    DatePicker,
    FilePicker,
    Input,
    KeyboardType,
    Slider,
    Switch,
    TextArea,
)
from tempestroid.widgets.layout import (
    Column,
    Container,
    Row,
    SafeArea,
    SafeAreaEdge,
    ScrollView,
    Stack,
)
from tempestroid.widgets.lists import (
    DEFAULT_WINDOW_SIZE,
    LazyColumn,
    LazyGrid,
    LazyRow,
    RefreshControl,
    SectionHeader,
    SectionList,
)
from tempestroid.widgets.media import Icon, Image, ImageFit
from tempestroid.widgets.navigation_widgets import (
    Navigator,
    RouteDrawer,
    TabBar,
    TabView,
)
from tempestroid.widgets.overlays import (
    ActionSheet,
    BottomSheet,
    Dialog,
    Menu,
    MenuItem,
    Popover,
    Toast,
    Tooltip,
)
from tempestroid.widgets.text import Text

__all__ = [
    "EventHandler",
    "TextChangeHandler",
    "ToggleHandler",
    "SlideHandler",
    "DateChangeHandler",
    "FileSelectHandler",
    "TapHandler",
    "LongPressHandler",
    "SwipeHandler",
    "RouteChangeHandler",
    "ScrollHandler",
    "RefreshHandler",
    "EndReachedHandler",
    "DismissHandler",
    "MenuSelectHandler",
    "handler_accepts_event",
    "Widget",
    "Component",
    "Text",
    "Button",
    "Column",
    "Row",
    "Container",
    "ScrollView",
    "SafeArea",
    "SafeAreaEdge",
    "Stack",
    "Animated",
    "AnimatedList",
    "Hero",
    "Shimmer",
    "Skeleton",
    "GestureDetector",
    "Navigator",
    "TabView",
    "TabBar",
    "RouteDrawer",
    "Input",
    "TextArea",
    "Checkbox",
    "Switch",
    "Slider",
    "KeyboardType",
    "DatePicker",
    "FilePicker",
    "Image",
    "ImageFit",
    "Icon",
    "ProgressBar",
    "Spinner",
    "DEFAULT_WINDOW_SIZE",
    "LazyColumn",
    "LazyRow",
    "LazyGrid",
    "SectionList",
    "RefreshControl",
    "SectionHeader",
    "Dialog",
    "BottomSheet",
    "Toast",
    "Tooltip",
    "Menu",
    "MenuItem",
    "Popover",
    "ActionSheet",
    "Event",
    "TapEvent",
    "TextChangeEvent",
    "ToggleEvent",
    "SlideEvent",
    "DateChangeEvent",
    "FileSelectEvent",
    "SwipeDirection",
    "LongPressEvent",
    "SwipeEvent",
    "RouteChangeEvent",
    "ScrollEvent",
    "RefreshEvent",
    "EndReachedEvent",
    "DismissEvent",
    "MenuSelectEvent",
    "EventValidationError",
    "parse_event",
]
