"""tempestroid — build native Android apps in typed Python.

Public surface: the typed style model, declarative widget primitives, typed
events, the reconciler (IR + diff), the app/state loop, and introspection. The
Qt simulator runner lives under ``tempestroid.renderers.qt`` (needs the ``qt``
extra) and is imported on demand.
"""

from importlib.metadata import PackageNotFoundError, version

from tempestroid.bridge import (
    BACK_TOKEN,
    Bridge,
    DeviceApp,
    EventMessage,
    JniBridge,
    LoopbackBridge,
    MountMessage,
    PatchMessage,
    run_device,
    serialize_node,
    serialize_patch,
)
from tempestroid.components import (
    Accordion,
    AppBar,
    Avatar,
    Badge,
    Banner,
    Breadcrumb,
    Burger,
    Calendar,
    Card,
    Chip,
    Clock,
    Divider,
    Drawer,
    EmptyState,
    Footer,
    Grid,
    Header,
    ListTile,
    NavBar,
    RadioGroup,
    Rating,
    Scaffold,
    SearchBar,
    SegmentedControl,
    Sidebar,
    Stepper,
    merge_style,
)
from tempestroid.core import (
    App,
    Insert,
    Node,
    Patch,
    Path,
    Remove,
    Reorder,
    Replace,
    Update,
    build,
    diff,
    event_catalog,
    introspect,
    widget_catalog,
)
from tempestroid.devices import (
    DEFAULT_DEVICE,
    Device,
)
from tempestroid.devserver import (
    DevServer,
    render_qr,
    run_dev_client,
    serve_device,
)
from tempestroid.native import notify
from tempestroid.navigation import NavStack, Route, routes_from_path
from tempestroid.renderers.compose import to_compose
from tempestroid.style import (
    AlignItems,
    Border,
    Color,
    Corners,
    Curve,
    Edge,
    FlexDirection,
    FontStyle,
    FontWeight,
    Gradient,
    GradientDirection,
    GradientStop,
    JustifyContent,
    Position,
    Shadow,
    SideBorder,
    StackAlign,
    Style,
    TextAlign,
    TextDecoration,
    TextOverflow,
    Transition,
)
from tempestroid.widgets import (
    Button,
    Checkbox,
    Column,
    Component,
    Container,
    DateChangeEvent,
    DatePicker,
    Event,
    EventHandler,
    EventValidationError,
    FilePicker,
    FileSelectEvent,
    GestureDetector,
    Icon,
    Image,
    ImageFit,
    Input,
    KeyboardType,
    LongPressEvent,
    LongPressHandler,
    Navigator,
    ProgressBar,
    RouteChangeEvent,
    RouteChangeHandler,
    RouteDrawer,
    Row,
    SafeArea,
    SafeAreaEdge,
    ScrollView,
    SlideEvent,
    Slider,
    Spinner,
    Stack,
    SwipeDirection,
    SwipeEvent,
    SwipeHandler,
    Switch,
    TabBar,
    TabView,
    TapEvent,
    TapHandler,
    Text,
    TextArea,
    TextChangeEvent,
    ToggleEvent,
    Widget,
    parse_event,
)

try:
    __version__ = version("tempestroid")
except PackageNotFoundError:  # running from a source tree without an install
    __version__ = "0.0.0"

__all__ = [
    "__version__",
    # Style
    "Style",
    "Color",
    "Edge",
    "Border",
    "SideBorder",
    "Corners",
    "Shadow",
    "GradientStop",
    "Gradient",
    "Transition",
    "FlexDirection",
    "JustifyContent",
    "AlignItems",
    "TextAlign",
    "FontWeight",
    "FontStyle",
    "TextDecoration",
    "TextOverflow",
    "GradientDirection",
    "Curve",
    "Position",
    "StackAlign",
    # Widgets
    "Widget",
    "Component",
    "Text",
    "Button",
    "Column",
    "Row",
    "Container",
    "ScrollView",
    "SafeArea",
    "SafeAreaEdge",
    "Stack",
    "GestureDetector",
    "Navigator",
    "TabView",
    "TabBar",
    "RouteDrawer",
    "Input",
    "TextArea",
    "Checkbox",
    "Switch",
    "Slider",
    "KeyboardType",
    "DatePicker",
    "FilePicker",
    "Image",
    "ImageFit",
    "Icon",
    "ProgressBar",
    "Spinner",
    "EventHandler",
    # Composite components (lower to primitives via Component.render)
    "AppBar",
    "Header",
    "Footer",
    "Sidebar",
    "Scaffold",
    "Grid",
    "NavBar",
    "Breadcrumb",
    "Burger",
    "Drawer",
    "Calendar",
    "Clock",
    "Card",
    "ListTile",
    "Avatar",
    "Divider",
    "SegmentedControl",
    "RadioGroup",
    "Chip",
    "Rating",
    "Stepper",
    "SearchBar",
    "Accordion",
    "Banner",
    "EmptyState",
    "Badge",
    "merge_style",
    # Gesture handlers (overlay + gestures)
    "TapHandler",
    "LongPressHandler",
    "SwipeHandler",
    "RouteChangeHandler",
    # Events (typed boundary contract)
    "Event",
    "TapEvent",
    "TextChangeEvent",
    "ToggleEvent",
    "SlideEvent",
    "DateChangeEvent",
    "FileSelectEvent",
    "SwipeDirection",
    "LongPressEvent",
    "SwipeEvent",
    "RouteChangeEvent",
    "EventValidationError",
    "parse_event",
    # Navigation (routes + stack)
    "Route",
    "NavStack",
    "routes_from_path",
    # Core (IR + reconciler)
    "Path",
    "Node",
    "Replace",
    "Update",
    "Insert",
    "Remove",
    "Reorder",
    "Patch",
    "build",
    "diff",
    "App",
    # Introspection
    "introspect",
    "widget_catalog",
    "event_catalog",
    # Compose renderer (Python side, phase B4)
    "to_compose",
    # Bridge (Python↔Kotlin boundary, phase B3)
    "BACK_TOKEN",
    "Bridge",
    "LoopbackBridge",
    "JniBridge",
    "run_device",
    "DeviceApp",
    "MountMessage",
    "PatchMessage",
    "EventMessage",
    "serialize_node",
    "serialize_patch",
    # Device presets (simulator viewport sizing)
    "Device",
    "DEFAULT_DEVICE",
    # Dev server (LAN code-push, phase B5)
    "DevServer",
    "run_dev_client",
    "serve_device",
    "render_qr",
    # Native capabilities (phase B6)
    "notify",
]
